-- AlterTable
ALTER TABLE "products"
  ADD COLUMN "staffSetup" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "staffOperate" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "lengthM" DOUBLE PRECISION,
  ADD COLUMN "widthM" DOUBLE PRECISION,
  ADD COLUMN "heightM" DOUBLE PRECISION,
  ADD COLUMN "weightKg" DOUBLE PRECISION,
  ADD COLUMN "truckSpaceUnits" INTEGER,
  ADD COLUMN "handlingFlags" TEXT[] DEFAULT ARRAY[]::TEXT[];
